SVC_LDAP = False
SVC_OXPASSPORT = True
SVC_OXSHIBBOLETH = True
SVC_MYSQL = True

PERSISTENCE_TYPE = "sql"
SQL_DB_DIALECT= "mysql"
SQL_DB_NAME = "gluu"
SQL_DB_HOST = "mysql"
SQL_DB_PORT = 3306
SQL_DB_USER = "gluu"
